version: yml.{build}
clone_depth: 5
cache: C:\Users\appveyor\.gradle\
build_script:
- cmd: gradlew --no-daemon assemble
test_script:
- cmd: .\gradlew --no-daemon check
artifacts:
- path: build\libs
  name: FEMP
- path: build\libs\Fire Emblem Multiplayer-SNAPSHOT.jar
  name: Client
on_failure:
- ps: 7z a ..\test_report.zip .\build\reports\tests\test\*
- ps: Push-AppveyorArtifact ..\test_report.zip